sudo: false
cache: yarn
language: node_js
env:
  global:
  - NODE_ENV='test'
  # DOCKER_USERNAME
  - secure: zvua+yVIlD+bKX7IpTxc10u/BwpydsOxyrE2PtAiKgpbBN8sP1r+d0UB1BJvvqYHfeYREu6/HdS6sMWG3pAUl0trLjuPeVWDuYBn2kH/c9p9yrC4qnJo483n2jpH/GnR6GBaoI/pwZfi7ZETURs89ZXo9I54aJHuJFHDL4YYBdtHgKyce8DwJrnM4SXjGe747RUdOd4J98lpSe5GV1wwcU5lSoV7g7oKAV7oo/4FOAQUlv2OJRIpEhgIYR9ccrdHBPndEqlUX2+Igg3Hj9Pw5JgYpzI+NMILCjN4LvnjTyh6W9Yu4ngPWkMTUUQYsLZ3e8FbVWRlmPqBarhH2ZZPYHQlCVQLdV9f3TzL8abi4qONPNfE7gKQuU/YKd6uMW/fIIbWaOWjGJ1DI8KakYvx25DoUZ9VIGUu5SkaItwV7GxfUt4h6b7povXJnfhnMM8aIFSNiuJhF4e3TJHnRgzKgfO/6eeWwgrR16bSJR0WTevXMedGs2tibOmV3ZrqBsCOjkP4DiLX4iI8tUFH//zI6euTz4Av2T3BJhAHI1oJ+pGZZF0sla7jUYs6bjFMr50Zy2PUt0oC4pW6d/pdWa/4rnGOZMZlu+BPeCHVVfR23cfRrZuSxuyu1w+FHOEb23yNRfFeOuOUwBXqJdczihr25iHGqDY3Hsrg2+xj+Xa87I4=
  # DOCKER_PASSWORD
  - secure: w6CJ5CHHDG3SUBA4UiPOZwPI8I+1xKmS/SqYHBV2o2XaZoacf4O4k3ahfGtyUPL0BW4k0aFMAqphFMV4Bgg4XTG/R+GXDXWmkkVOsVyXp3GlfSM+32ZmtZ5IXsMczXus4f/8V4GVIJxGToKeB0GBV32lRBvu6oLY9OIkCUf6KSSr5PTzw65NyG+EyONHEyZ0zyyS5tThvDKVYqTTwhr3XhDjnfKJtvfpnSVI1CAOTFR9NQeNo5OkBtDMwrOdS+OQXjJYzoymevNiQ070WsEw6BCuE71ywkpzV3gAw3SZ7pgrEkkJ1t3YkaxeiStt5KGMJcneW4MvImYwFuj5ypwjrmKEP+Xj6Z12PCmxDGO+LGV3hAm5a6uH3FnwaqSQppV53dabCj42V64pX655saktTIEm6ojEtFYugyY3ilgGz4jKx6CnLII3yiHaaS++oZ5xb08iUHNjFD6iS4VnTj7Vhmh/lsn33ZWgLJaqhJlPq3DkTsIZQ57bkYa3YOvWZTFt41CrcFbreTBxmV68qRqVVtcweq/wWV8fcK+6dAlVftNhV0Mz6VshXQ1BCnQcyl7r+8HyrlVwVXLKdpvt/ICgdVvcmESzy4ZrIWNTmx+8yNVPpj/pZDEVNtsaXYbr/qXuNKP03UOtaMYLBpM5SCP/Sx7VPrQTvY2dg6CVV1o6Fr4=
branches:
  only:
  - master
before_install:
- cd ./$SERVICE
- nvm install
- nvm use
- node --version
- SERVICE=$SERVICE make ensure-dependencies
script:
- make qa
- TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make brand
- DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make build
matrix:
  include:
  - env: SERVICE=recipes-api
    services:
    - docker
  - env: SERVICE=recipes-crawler
    services:
    - docker